# Generated by Django 5.1.5 on 2025-01-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_name', models.CharField(max_length=64)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_name', models.CharField(max_length=256)),
                ('Zogolovok', models.TextField()),
                ('osnovnoy_tekst', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('News_New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.new')),
            ],
        ),
    ]
